[project]
name = "TheCommander"
version = "0.1.0"
description = "A Flask-based AI agent system integrating Anthropic Claude and OpenAI for natural language understanding, command execution, and workflow automation."
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.50.0",
    "email-validator>=2.2.0",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "openai>=1.76.0",
    "psutil>=7.0.0",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.3",
    "trafilatura>=2.0.0",
]
